<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtlasBalance.Domain\AtlasBalance.Domain.csproj" />
    <ProjectReference Include="..\AtlasBalance.Infrastructure\AtlasBalance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
